# ===== CONFIGURACIÓN GENERAL =====
spring.application.name=ChifaXinYan
server.port=8080

# ===== POSTGRESQL CONFIGURATION =====
spring.datasource.url=jdbc:postgresql://localhost:5432/Salon_xin_yan
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / HIBERNATE CONFIGURATION =====
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

<<<<<<< HEAD
# ===== TRANSACTION LOGGING =====
logging.level.org.springframework.transaction=DEBUG
logging.level.org.hibernate.transaction=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# ===== LOGGING =====
logging.level.apf2.ChifaXinYan=DEBUG
logging.level.org.springframework.web=INFO

# ===== JWT CONFIGURATION =====
app.jwt.secret=XinYanImperialChifaWok2026TokenU1
app.jwt.expiration=86400000

# ===== FILE UPLOAD=====
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
=======
# Logging
logging.level.apf2.ChifaXinYan=DEBUG

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5434/desarrollo
spring.datasource.username=postgres
spring.datasource.password=galaxylife
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
>>>>>>> 0a71042947e863f58f51a24e38f758253f8febe9
