spring.application.name=ChifaXinYan
server.port=8080

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Static Resources 
spring.web.resources.static-locations=classpath:/static/
spring.web.resources.cache.period=0

# Logging
logging.level.apf1.ChifaXinYan=DEBUG
