spring.application.name=ChifaXinYan
server.port=8080

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Static Resources 
spring.web.resources.static-locations=classpath:/static/
spring.web.resources.cache.period=0

# Logging
logging.level.apf2.ChifaXinYan=DEBUG

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5434/desarrollo
spring.datasource.username=postgres
spring.datasource.password=galaxylife
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
